force-app/main/default/objects/Account_Business_Plan__c/Account_Business_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Business Plan</label>
    <nameField>
        <label>Account Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Business Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Business_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Business plans</relationshipLabel>
    <relationshipName>Account_Business_plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Business_Plan__c/fields/Next_Steps__c.field-meta.xml
<CustomField>
    <fullName>Next_Steps__c</fullName>
    <inlineHelpText>Next steps for the account.</inlineHelpText>
    <label>Next Steps</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Business_Plan__c/fields/Plan_Status__c.field-meta.xml
<CustomField>
    <fullName>Plan_Status__c</fullName>
    <label>Plan Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Business_Plan__c/fields/Plan_Text__c.field-meta.xml
<CustomField>
    <fullName>Plan_Text__c</fullName>
    <inlineHelpText>The text of the business plan for the account.</inlineHelpText>
    <label>Plan Text</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Business_Plan__c/fields/Planned_Activities__c.field-meta.xml
<CustomField>
    <fullName>Planned_Activities__c</fullName>
    <inlineHelpText>Planned activities for the account.</inlineHelpText>
    <label>Planned Activities</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Business_Plan__c/fields/Target_Margin__c.field-meta.xml
<CustomField>
    <fullName>Target_Margin__c</fullName>
    <inlineHelpText>The target margin for the account.</inlineHelpText>
    <label>Target Margin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account_Business_Plan__c/fields/Target_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Target_Revenue__c</fullName>
    <inlineHelpText>The target revenue for the account.</inlineHelpText>
    <label>Target Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AccountBusinessPlanController.cls
public with sharing class AccountBusinessPlanController {
    @AuraEnabled(cacheable=true)
    public static List<Account_Business_Plan__c> getAccountBusinessPlans(Id accountId) {
        return [SELECT Id, Plan_Text__c, Plan_Status__c, Target_Revenue__c, Target_Margin__c, Planned_Activities__c, Next_Steps__c
                FROM Account_Business_Plan__c
                WHERE Account__c = :accountId];
    }
}